# Use an official Node.js runtime as a parent image
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json for npm install
COPY app/vote-frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY app/vote-frontend/. .

# Expose port 3000 to the outside world
EXPOSE 3000

# Command to run the server
CMD ["node", "server.js"]