FROM python:3.9-slim

WORKDIR /app

COPY app/backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app/backend/. .

EXPOSE 5000

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5001", "app:app"]